[build-system]
requires = [ "poetry-core", "setuptools",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = true
name = "veganminecraft"
version = "1.0.0"
description = ""
license = "GPL-3.0-or-later"
authors = [ "Brandon Graham Cobb <brandongrahamcobb@icloud.com>",]
readme = "README.md"
homepage = "https://brandongcobb.com"
repository = "https://github.com/brandongrahamcobb/veganminecraft-py.git"
keywords = [ "json", "python", "yaml",]
packages = [{include = "veganminecraft", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
aiohttp = "*"
python-dotenv = "*"
docker = "*"
discord-py = {git = "https://github.com/Rapptz/discord.py.git"}

[tool.poetry.scripts]
vyrtuous = "veganminecraft.main:run"
